### ISSUE TITLE
Repo & NPM package is missing build

### ISSUE THREAD

**Issue by SimulatedGREG** [matisoffn/vue-mask#1]
This repo is pointless without the actual directive.

**Comment by matisoffn** [comment]
@SimulatedGREG I haven't built this yet.  Would you like me to destroy the repo or wait until I build this for everybody to use for free?

**Comment by SimulatedGREG** [comment]
Sorry for the confusion. It's just odd that there's documentation on how to use this, but there aren't any source files or any indication as to whether or not this repo in still in development.

**Comment by matisoffn** [comment]
I wouldn't indicate a sparse README as documentation.  I planned on building a simple masking library/directive for Vue but haven't gotten around to it.

No need to be negative.  If you're keen on building something like this, feel free to do so and I'll get rid of my repo.

**Comment by SimulatedGREG** [comment]
Well yeah that makes sense if I found this in github, but I found it searching npm, which doesn't show the document tree. So obviously trying to include this made me come to github and check after getting an error lol. I'd love for you to complete this, but if not I'll just find something else.

**Comment by matisoffn** [comment]
I'll have it done within the next two weeks, just for you @SimulatedGREG

**Comment by SimulatedGREG** [comment]
Alright thanks. And I understand what you're saying, but if people searching something on NPM, it's pretty much expected there's something already ready to use.

**Comment by matisoffn** [comment]
I get it.  But remember, this is open-source and **free** software, so don't hold high standards and expectations.

**Comment by SimulatedGREG** [comment]
Yes which led me to believe the build was missing because of gitignore. Either way this repo is a little misleading being on npm. There's a least 30 people this month that tried using this. I'm just the first to actually say anything lol.

**Comment by jackel27** [comment]
Hey, so is there something wrong with the npm? What's going on? Tried using this.. Just curious.. oh wait nm.. wow.

**Comment by Rafase282** [comment]
I was lurking but just wanted to say this, free and opensource does not necessarily mean it is crap or expected to not be in good standards. @matisoffn

**Comment by matisoffn** [comment]
@Rafase282 of course, but don't go opening issues with a negative attitude for a project that hasn't been built but is published.

Just check out the source before including a bunch of code in your project.

**Comment by AkiraLaine** [comment]
@matisoffn If you have a NPM package published and it has nothing in it - what's the point of publishing it in the first place? You can just publish it when you have something :smile:

**Comment by airtonix** [comment]
If I were following TDD, i'd create a blank repo with instructions on how I saw it being used.

@matisoffn Keep going. I'd recommend you move forward as such:
- define requirements in gherkin syntax
- define the code that provides the service
-- write unit tests as per requirements for the services
-- write the code until tests pass
- define the code that provides the component
-- write e2e tests as per requirements for the component.
-- write code until tests pass.

There's a nice project skeleton here to provide the foundation for doing all this here: 
- https://github.com/vuejs-templates/browserify , or
- https://github.com/vuejs-templates/webpack
